# Conda environment for running gem5 and ChampSim on UTCS machines, but
# self-contained.
#
# That is, this version of the environment has every library, package, and 
# tool included, for systems which may not have everything installed.
#
# TODO: Fix excessive -Wnon-virtual-dtor warnings when compiling.

name: cs-395t-full
channels:
  - conda-forge
dependencies:
  - boost-cpp
  - cmake
  - capstone
  - doxygen
  - elfutils
  - gcc=13
  - gperftools
  - gxx=13
  - hdf5
  - libpng
  - libprotobuf
  - m4
  - mold
  - mypy
  - pkg-config
  - pre-commit
  - protobuf
  - python=3.13
  - pydot
  - scons
  - tk
  - zlib
